### ISSUE TITLE
[FEATURE REQUEST] Authentication with Api Key 

### ISSUE THREAD

**Issue by LucaSoato** [Chavaillaz/elasticsearch-log4j-appender#2]
Hi,
first of all thanks for the help, this is a very cool project! :) 
Do you know if there's a way to make it work with api-key based authentication? 
If you can give me few hints I can try to make it work and send you a PR! 
Thanks again,
Luca

**Comment by Chavjoh** [comment]
Hello,

Sorry for my late reply, I didn't check my notifications for a while :) I published today a new version 2.1.2 with the possibility to give an API Key to authenticate. 

Have fun!
